title: Joystick Control System
author: MWMathis Lab
logo: docs/images/logo.png
only_build_toc_files: true

sphinx:
  config:
    autodoc_mock_imports: "list"
  extra_extensions:
    - numpydoc

execute:
  execute_notebooks: "off"

html:
  extra_navbar: ""
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div>Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>.</div>

repository:
  url: https://github.com/AdaptiveMotorControlLab/JoystickControlSystem #change me
  path_to_book: docs
  branch: master

launch_buttons:
  colab_url: "https://colab.research.google.com/github/AdaptiveMotorControlLab/examples/yourdemo.ipynb"
